# Generated by Django 3.2.4 on 2021-11-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='profile',
            field=models.ManyToManyField(related_name='liked_blog', to='BlogApp.Profile'),
        ),
    ]
