# Generated by Django 3.2.4 on 2021-11-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_blogmodel_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='profile',
            new_name='likes',
        ),
    ]
