# Generated by Django 3.2.4 on 2021-11-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_blogmodel_total_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='total_likes',
            new_name='tot_likes',
        ),
    ]
