# Generated by Django 3.2.4 on 2021-11-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_rename_total_likes_blogmodel_tot_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tot_likes',
        ),
    ]
