# Generated by Django 3.2.4 on 2021-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_remove_blogmodel_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='sharestring',
            field=models.CharField(default='nulll', max_length=10000),
        ),
    ]
